name: End-to-end tests 🧪
on: [push]
env:
  USERNAME: "Teste Giovanni"
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        id: step_one
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0
      - name: Access the environment variable
        run: |
          echo "The saved state is:"
          echo "${{ env.USERNAME }}"